### ISSUE TITLE
ColorScheme Support

### ISSUE THREAD

**Issue by cyrilzakka** [lfroms/fluid-menu-bar-extra#2]
Hello,

Hope you're well! I'm looking into integrating this package into my application but I'm having trouble porting my `colorScheme` detection code:

```
    @Environment(\.colorScheme) var colorScheme
    @AppStorage("appTheme") private var defaultAppearance: AppearanceKeys = .system
    var body: some Scene {
        MenuBarExtra("Notus", image: "notus", content: {
            ContentView()
                .preferredColorScheme(defaultAppearance == .light ? .light : defaultAppearance == .dark ? .dark : colorScheme)
        })
}
```

Accessing the color scheme in AppDelegate results in the following warning:
```
Accessing Environment<ColorScheme>'s value outside of being installed on a View. This will always read the default value and will not update.
```

Finally, do you have any examples of the Menu's `scenePhase` being used?

**Comment by lfroms** [comment]
Hi there!  Because `AppDelegate` is a plain object, not a `View`-conforming struct, it it isn't stateful, which means you can't use SwiftUI property wrappers in it.  Instead, you'll need to move your `colorScheme` and `defaultAppearance` properties to _inside_ your `ContentView`, like so:

```swift
// ContentView.swift

struct ContentView: View {
    @Environment(\.colorScheme) var colorScheme
    @AppStorage("appTheme") private var defaultAppearance: AppearanceKeys = .system

    var body: some View {
        SomeChildView()
            .preferredColorScheme(defaultAppearance == .light ? .light : defaultAppearance == .dark ? .dark : colorScheme)
    }
}
```

If you have more than one child view, you can either wrap them in a new `View` struct, or use a `Group { }` to apply the `preferredColorScheme` modifier to all of them.

As for `scenePhase`, check out the following documentation: https://developer.apple.com/documentation/swiftui/scenephase.  Again, the property and `@Environment` property wrapper must be used in a `View`, such as your `ContentView`.
